export const content = {
    "uk": {
        "aboutUs": "Про нас",
        "howDoesItWork": "Як це працює",
        "whereDoWeWork": "Де працюємо",
        "faq": "FAQ",
        "contacts": "Контакти",
        "exchange": "Конвертуй крипту та фіат без обмежень",
        "formTitle": "Конвертувати",
        "description": "Працює на смарт-контрактах",
        "pointer": "Гортайте вниз",
        "social": "Наші соціальні мережі",
        "platformTitle": "Провідна платформа для конвертування цифрових активів",
        "platformText": "Відкрийте для себе передову платформу для конвертації цифрових активів, яка вигідно виділяється завдяки своєму фокусу на ефективному конвертуванні. Наш широкий спектр послуг у сфері торгівлі та управління цифровими активами розроблений, щоб задовольнити найрізноманітніші торгові потреби.",
        "exchangeTitle": "Здійсніть конвертацію за 3 кроки",
        "exchangeButton": "Почати конвертування",
        "stepOne": "Крок 1",
        "stepTwo": "Крок 2",
        "stepThree": "Крок 3",
        "stepTitle1": "Знайдіть монети",
        "stepTitle2": "Безпечно конвертуйте",
        "stepTitle3": "Отримайте результат",
        "stepText1": "Розпочніть свій шлях знайомства з криптовалютами, знаходячи найкращі монети на нашій платформі.",
        "stepText2": "Забезпечте безпеку своїх цифрових активів під час їх конвертації, користуючись нашим надійним сервісом.",
        "stepText3": "Отримайте миттєвий результат конвертації цифрових активів з нашою ефективною та швидкою платформою.",
        "countriesTitle": "Додайте вашу країну",
        "addMycountry": "Підключити мою країну",
        "au": "Австралія",
        "at": "Австрія",
        "az": "Азербайджан",
        "al": "Албанія",
        "dz": "Алжир",
        "ao": "Ангола",
        "ar": "Аргентина",
        "af": "Афганістан",
        "bd": "Бангладеш",
        "bz": "Беліз",
        "be": "Бельгія",
        "bj": "Бенін",
        "by": "Білорусь",
        "bg": "Болгарія",
        "bo": "Болівія",
        "ba": "Боснія і Герцеговина",
        "bw": "Ботсвана",
        "br": "Бразилія",
        "bf": "Буркіна-Фасо",
        "bi": "Бурунді",
        "bt": "Бутан",
        "gb": "Велика Британія",
        "ve": "Венесуела",
        "vn": "В'єтнам",
        "am": "Вірменія",
        "ga": "Габон",
        "ht": "Гаїті",
        "gy": "Гаяна",
        "gm": "Гамбія",
        "gh": "Гана",
        "gt": "Гватемала",
        "gf": "Гвіана",
        "gn": "Гвінея",
        "gw": "Гвінея-Бісау",
        "hn": "Гондурас",
        "gr": "Греція",
        "ge": "Грузія",
        "gl": "Гренландія",
        "dk": "Данія",
        "cd": "ДР Конго",
        "dj": "Джибуті",
        "do": "Домініканська Республіка",
        "ec": "Еквадор",
        "gq": "Екваторіальна Гвінея",
        "sz": "Есватині",
        "er": "Еритрея",
        "ee": "Естонія",
        "et": "Ефіопія",
        "eg": "Єгипет",
        "ye": "Ємен",
        "zm": "Замбія",
        "zw": "Зімбабве",
        "il": "Ізраїль",
        "in": "Індія",
        "iq": "Ірак",
        "ir": "Іран",
        "ie": "Ірландія",
        "is": "Ісландія",
        "es": "Іспанія",
        "it": "Італія",
        "jo": "Йорданія",
        "kz": "Казахстан",
        "kh": "Камбоджа",
        "cm": "Камерун",
        "ca": "Канада",
        "qa": "Катар",
        "ke": "Кенія",
        "kg": "Киргизстан",
        "cn": "Китайська Народна Республіка",
        "cy": "Кіпр",
        "co": "Колумбія",
        "cg": "Республіка Конго",
        "cr": "Коста-Рика",
        "ci": "Кот-д'Івуар",
        "cu": "Куба",
        "kw": "Кувейт",
        "la": "Лаос",
        "lv": "Латвія",
        "ls": "Лесото",
        "lt": "Литва",
        "lr": "Ліберія",
        "lb": "Ліван",
        "ly": "Лівія",
        "lu": "Люксембург",
        "mr": "Мавританія",
        "mg": "Мадагаскар",
        "mw": "Малаві",
        "my": "Малайзія",
        "ml": "Малі",
        "ma": "Марокко",
        "mx": "Мексика",
        "mz": "Мозамбік",
        "md": "Молдова",
        "mn": "Монголія",
        "mm": "М'янма",
        "na": "Намібія",
        "np": "Непал",
        "ne": "Нігер",
        "ng": "Нігерія",
        "nl": "Нідерланди",
        "ni": "Нікарагуа",
        "de": "Німеччина",
        "nz": "Нова Зеландія",
        "no": "Норвегія",
        "ae": "ОАЕ",
        "om": "Оман",
        "pk": "Пакистан",
        "pa": "Панама",
        "pg": "Папуа Нова Гвінея",
        "py": "Парагвай",
        "pe": "Перу",
        "za": "ПАР",
        "gs": "Південна Корея",
        "kp": "Північна Корея",
        "mk": "Північна Македонія",
        "pl": "Польща",
        "pt": "Португалія",
        "pr": "Пуерто-Рико",
        "ru": "Росія",
        "rw": "Руанда",
        "ro": "Румунія",
        "sv": "Сальвадор",
        "sa": "Саудівська Аравія",
        "sn": "Сенегал",
        "rs": "Сербія",
        "sy": "Сирія",
        "sk": "Словаччина",
        "si": "Словенія",
        "so": "Сомалі",
        "us": "США",
        "sd": "Судан",
        "sr": "Суринам",
        "tl": "Східний Тимор",
        "sl": "Сьєрра-Леоне",
        "tj": "Таджикистан",
        "th": "Таїланд",
        "tw": "Тайвань",
        "tz": "Танзанія",
        "tg": "Того",
        "tr": "Туреччина",
        "tm": "Туркменістан",
        "tn": "Туніс",
        "ug": "Уганда",
        "hu": "Угорщина",
        "uz": "Узбекистан",
        "ua": "Україна",
        "uy": "Уругвай",
        "fi": "Фінляндія",
        "ph": "Філіпіни",
        "fr": "Франція",
        "fk": "Фолклендські острови",
        "hr": "Хорватія",
        "cf": "Центральноафриканська Республіка",
        "td": "Чад",
        "cz": "Чехія",
        "cl": "Чилі",
        "me": "Чорногорія",
        "ch": "Швейцарія",
        "se": "Швеція",
        "lk": "Шрі-Ланка",
        "jm": "Ямайка",
        "jp": "Японія",
        "faqText": "Знайдіть відповіді на запитання, що цікавлять",        
        "questionTitle1": "Які криптовалюти можна конвертувати на вашому сервісі без комісій?",
        "answerText1": "Ви можете конвертувати будь-яку популярну криптовалюту, таку як Bitcoin, Ethereum, Litecoin і багато інших, без будь-яких комісій.",
        "questionTitle2": "Як швидко відбувається процес конвертації криптовалюти на вашому сервісі?",
        "answerText2": "Конвертація криптовалюти майже миттєва. Ваші кошти будуть доступні в обраній вами криптовалюті найшвидше, як це можливо.",
        "questionTitle3": "Чому ваш сервіс не взимкує комісії за конвертацію криптовалюти?",
        "answerText3": "Ми вирішили не встановлювати комісії, щоб зробити процес конвертації максимально доступним та прозорим для наших користувачів.",
        "questionTitle4": "Чи існує обмеження на суму конвертації без комісій?",
        "answerText4": "Наразі у нас немає обмежень на суму конвертації без комісій. Ви можете конвертувати стільки, скільки потрібно.",
        "questionTitle5": "Які заходи безпеки забезпечують конфіденційність моїх транзакцій?",
        "answerText5": "Ми використовуємо передові технології шифрування, щоб забезпечити конфіденційність вашої інформації та транзакцій.",
        "questionTitle6": "Чи можна скасувати або відмінити конвертацію після її запуску?",
        "answerText6": "На жаль, конвертацію неможливо скасувати або відмінити після того, як вона розпочалася. Будь ласка, перевірте всі дані перед підтвердженням.",
        "questionTitle7": "Чи є які-небудь обмеження на кількість операцій конвертації за день чи за місяць?",
        "answerText7": "У нас немає обмежень на кількість операцій конвертації. Ви можете використовувати наш сервіс стільки разів, скільки вам потрібно, без обмежень."
    },
    
    "ru": {
        "aboutUs": "О нас",
        "howDoesItWork": "Как это работает",
        "whereDoWeWork": "Где мы работаем",
        "faq": "FAQ",
        "contacts": "Контакты",
        "exchange": "Конвертируйте криптовалюту и фиат без ограничений",
        "formTitle": "Конвертировать",
        "description": "Работает на смарт-контрактах",
        "pointer": "Листайте вниз",
        "social": "Наши социальные сети",
        "platformTitle": "Ведущая платформа для конвертации цифровых активов",
        "platformText": "Откройте для себя передовую платформу для конвертации цифровых активов, которая выделяется своим уклоном в эффективную конвертацию. Наш широкий спектр услуг в сфере торговли и управления цифровыми активами разработан, чтобы удовлетворить самые разнообразные торговые потребности.",
        "exchangeTitle": "Произведите конвертацию за 3 шага",
        "exchangeButton": "Начать конвертацию",
        "stepOne": "Шаг 1",
        "stepTwo": "Шаг 2",
        "stepThree": "Шаг 3",
        "stepTitle1": "Найдите монеты",
        "stepTitle2": "Безопасно конвертируйте",
        "stepTitle3": "Получите результат",
        "stepText1": "Начните свой путь знакомства с криптовалютами, находя лучшие монеты на нашей платформе.",
        "stepText2": "Обеспечьте безопасность ваших цифровых активов во время их конвертации, используя наш надежный сервис.",
        "stepText3": "Получите мгновенный результат конвертации цифровых активов с нашей эффективной и быстрой платформой.",
        "countriesTitle": "Добавьте вашу страну",
        "addMycountry": "Подключить мою страну",
        "au": "Австралия",
        "at": "Австрия",
        "az": "Азербайджан",
        "al": "Албания",
        "dz": "Алжир",
        "ao": "Ангола",
        "ar": "Аргентина",
        "af": "Афганистан",
        "bd": "Бангладеш",
        "bz": "Белиз",
        "be": "Бельгия",
        "bj": "Бенин",
        "by": "Беларусь",
        "bg": "Болгария",
        "bo": "Боливия",
        "ba": "Босния и Герцеговина",
        "bw": "Ботсвана",
        "br": "Бразилия",
        "bf": "Буркина-Фасо",
        "bi": "Бурунди",
        "bt": "Бутан",
        "gb": "Великобритания",
        "ve": "Венесуэла",
        "vn": "Вьетнам",
        "am": "Армения",
        "ga": "Габон",
        "ht": "Гаити",
        "gy": "Гайана",
        "gm": "Гамбия",
        "gh": "Гана",
        "gt": "Гватемала",
        "gf": "Гвиана",
        "gn": "Гвинея",
        "gw": "Гвинея-Бисау",
        "hn": "Гондурас",
        "gr": "Греция",
        "ge": "Грузия",
        "gl": "Гренландия",
        "dk": "Дания",
        "cd": "ДР Конго",
        "dj": "Джибути",
        "do": "Доминиканская Республика",
        "ec": "Эквадор",
        "gq": "Экваториальная Гвинея",
        "sz": "Эсватине",
        "er": "Эритрея",
        "ee": "Эстония",
        "et": "Эфиопия",
        "eg": "Египет",
        "ye": "Йемен",
        "zm": "Замбия",
        "zw": "Зимбабве",
        "il": "Израиль",
        "in": "Индия",
        "iq": "Ирак",
        "ir": "Иран",
        "ie": "Ирландия",
        "is": "Исландия",
        "es": "Испания",
        "it": "Италия",
        "jo": "Иордания",
        "kz": "Казахстан",
        "kh": "Камбоджа",
        "cm": "Камерун",
        "ca": "Канада",
        "qa": "Катар",
        "ke": "Кения",
        "kg": "Кыргызстан",
        "cn": "Китайская Народная Республика",
        "cy": "Кипр",
        "co": "Колумбия",
        "cg": "Республика Конго",
        "cr": "Коста-Рика",
        "ci": "Кот-д'Ивуар",
        "cu": "Куба",
        "kw": "Кувейт",
        "la": "Лаос",
        "lv": "Латвия",
        "ls": "Лесото",
        "lt": "Литва",
        "lr": "Либерия",
        "lb": "Ливан",
        "ly": "Ливия",
        "lu": "Люксембург",
        "mr": "Мавритания",
        "mg": "Мадагаскар",
        "mw": "Малави",
        "my": "Малайзия",
        "ml": "Мали",
        "ma": "Марокко",
        "mx": "Мексика",
        "mz": "Мозамбик",
        "md": "Молдова",
        "mn": "Монголия",
        "mm": "Мьянма",
        "na": "Намибия",
        "np": "Непал",
        "ne": "Нигер",
        "ng": "Нигерия",
        "nl": "Нидерланды",
        "ni": "Никарагуа",
        "de": "Германия",
        "nz": "Новая Зеландия",
        "no": "Норвегия",
        "ae": "ОАЭ",
        "om": "Оман",
        "pk": "Пакистан",
        "pa": "Панама",
        "pg": "Папуа Новая Гвинея",
        "py": "Парагвай",
        "pe": "Перу",
        "za": "ЮАР",
        "gs": "Южная Корея",
        "kp": "Северная Корея",
        "mk": "Северная Македония",
        "pl": "Польша",
        "pt": "Португалия",
        "pr": "Пуэрто-Рико",
        "ru": "Россия",
        "rw": "Руанда",
        "ro": "Румыния",
        "sv": "Сальвадор",
        "sa": "Саудовская Аравия",
        "sn": "Сенегал",
        "rs": "Сербия",
        "sy": "Сирия",
        "sk": "Словакия",
        "si": "Словения",
        "so": "Сомали",
        "us": "США",
        "SD": "Судан",
        "sr": "Суринам",
        "tl": "Восточный Тимор",
        "sl": "Сьерра-Леоне",
        "tj": "Таджикистан",
        "th": "Таиланд",
        "tw": "Тайвань",
        "tz": "Танзания",
        "tg": "Того",
        "tr": "Турция",
        "tm": "Туркменистан",
        "tn": "Тунис",
        "ug": "Уганда",
        "hu": "Венгрия",
        "uz": "Узбекистан",
        "ua": "Украина",
        "uy": "Уругвай",
        "fi": "Финляндия",
        "ph": "Филиппины",
        "fr": "Франция",
        "fk": "Фолклендские острова",
        "hr": "Хорватия",
        "cf": "Центральноафриканская Республика",
        "td": "Чад",
        "cz": "Чехия",
        "cl": "Чили",
        "me": "Черногория",
        "ch": "Швейцария",
        "se": "Швеция",
        "lk": "Шри-Ланка",
        "jm": "Ямайка",
        "jp": "Япония",
        "faqText": "Найдите ответы на интересующие вопросы",
        "questionTitle1": "Какие криптовалюты можно конвертировать на вашем сервисе без комиссий?",
        "answerText1": "Вы можете конвертировать любую популярную криптовалюту, такую как Bitcoin, Ethereum, Litecoin и многие другие, без каких-либо комиссий.",
        "questionTitle2": "Как быстро происходит процесс конвертации криптовалюты на вашем сервисе?",
        "answerText2": "Конвертация криптовалюты почти мгновенна. Ваши средства будут доступны в выбранной вами криптовалюте как можно скорее.",
        "questionTitle3": "Почему ваш сервис не взимает комиссии за конвертацию криптовалюты?",
        "answerText3": "Мы решили не устанавливать комиссии, чтобы сделать процесс конвертации максимально доступным и прозрачным для наших пользователей.",
        "questionTitle4": "Есть ли ограничение на сумму конвертации без комиссий?",
        "answerText4": "На данный момент у нас нет ограничений на сумму конвертации без комиссий. Вы можете конвертировать столько, сколько необходимо.",
        "questionTitle5": "Какие меры безопасности обеспечивают конфиденциальность моих транзакций?",
        "answerText5": "Мы используем передовые технологии шифрования для обеспечения конфиденциальности вашей информации и транзакций.",
        "questionTitle6": "Можно ли отменить или отозвать конвертацию после ее запуска?",
        "answerText6": "К сожалению, конвертацию нельзя отменить или отозвать после ее запуска. Пожалуйста, проверьте все данные перед подтверждением.",
        "questionTitle7": "Есть ли какие-либо ограничения на количество операций конвертации в день или в месяц?",
        "answerText7": "У нас нет ограничений на количество операций конвертации. Вы можете использовать наш сервис столько раз, сколько вам нужно, без ограничений.",
    }
};

export const contries = [
    {
        "name": "Австралія",
        "iso": "AU",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofaustralia_6595.png",
    },
    {
        "name": "Австрія",
        "iso": "AT",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/austria_flags_flag_16972.png",
    },
    {
        "name": "Азербайджан",
        "iso": "AZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/azerbaijanflag_6593.png",
    },
    {
        "name": "Албанія",
        "iso": "AL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofalbania_6606.png",
    },
    {
        "name": "Алжир",
        "iso": "DZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofalgeria_6605.png",
    },
    {
        "name": "Ангола",
        "iso": "AO",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofAngola_6602.png",
    },
    {
        "name": "Аргентина",
        "iso": "AR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/argentina_flags_flag_16969.png",
    },
    {
        "name": "Афганістан",
        "iso": "AF",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/afghanistan_flags_flag_16967.png",
    },
    {
        "name": "Бангладеш",
        "iso": "BD",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/bangladeshflag_6590.png",
    },
    {
        "name": "Беліз",
        "iso": "BZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofBelize_6586.png",
    },
    {
        "name": "Бельгія",
        "iso": "BE",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/Belgiumflag_6587.png",
    },
    {
        "name": "Бенін",
        "iso": "BJ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/beninflag_6585.png",
    },
    {
        "name": "Білорусь",
        "iso": "BY",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/belarus_flags_flag_16975.png",
    },
    {
        "name": "Болгарія",
        "iso": "BG",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/bulgaria_flags_flag_16980.png",
    },
    {
        "name": "Болівія",
        "iso": "BO",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofBolivia_6581.png",
    },
    {
        "name": "Боснія і Герцеговина",
        "iso": "BA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/bosnia_and_herzegovina_flags_flag_16977.png",
    },
    {
        "name": "Ботсвана",
        "iso": "BW",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/botswana_flags_flag_16978.png",
    },
    {
        "name": "Бразилія",
        "iso": "BR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/brazil_flags_flag_16979.png",
    },
    {
        "name": "Буркіна-Фасо",
        "iso": "BF",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/burkinafasoflag_6572.png",
    },
    {
        "name": "Бурунді",
        "iso": "BI",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofburundi_6570.png",
    },
    {
        "name": "Бутан",
        "iso": "BT",
        "flag": "https://www.google.com.ua/url?sa=i&url=https%3A%2F%2Fuk.m.wikipedia.org%2Fwiki%2F%25D0%25A4%25D0%25B0%25D0%25B9%25D0%25BB%3AFlag_of_Bhutan.svg&psig=AOvVaw0QAYyeCjmteTqJ0ALY0wSR&ust=1702308990228000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNC8jK-ZhYMDFQAAAAAdAAAAABAD",
    },
    {
        "name": "Велика Британія",
        "iso": "GB",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/united_kingdom_flags_flag_17079.png",
    },
    {
        "name": "Венесуела",
        "iso": "VE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/venezuela_flags_flag_17083.png",
    },
    {
        "name": "В'єтнам",
        "iso": "VN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/vietnam_flags_flag_17084.png",
    },
    {
        "name": "Вірменія",
        "iso": "AM",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/armenia_flags_flag_16970.png",
    },
    {
        "name": "Габон",
        "iso": "GA",
        "flag": "https://cdn.icon-icons.com/icons2/1573/PNG/512/2361504-flag-gabon_107797.png",
    },
    {
        "name": "Гаїті",
        "iso": "HT",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofhaiti_6510.png",
    },
    {
        "name": "Гаяна",
        "iso": "GY",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/GuyanaFlag_6511.png",
    },
    {
        "name": "Гамбія",
        "iso": "GM",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofGambia_6525.png",
    },
    {
        "name": "Гана",
        "iso": "GH",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/ghana_flags_flag_17002.png",
    },
    {
        "name": "Гватемала",
        "iso": "GT",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/guatemala_flags_flag_17004.png",
    },
    {
        "name": "Гвіана",
        "iso": "GF",
        "flag": "https://cdn.icon-icons.com/icons2/1694/PNG/512/gffrenchguianaflag_111783.png",
    },
    {
        "name": "Гвінея",
        "iso": "GN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/guinea_flags_flag_17007.png",
    },
    {
        "name": "Гвінея-Бісау",
        "iso": "GW",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/guinea_bissau_flags_flag_17006.png",
    },
    {
        "name": "Гондурас",
        "iso": "HN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/honduras_flags_flag_17008.png",
    },
    {
        "name": "Греція",
        "iso": "GR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/greece_flags_flag_17003.png",
    },
    {
        "name": "Грузія",
        "iso": "GE",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/georgiaflag_6524.png",
    },
    {
        "name": "Гренландія",
        "iso": "GL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/GreenlandFlag_6519.png",
    },
    {
        "name": "Данія",
        "iso": "DK",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/denmark_flags_flag_16990.png",
    },
    {
        "name": "ДР Конго",
        "iso": "CD",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/kinshasacongoflag_congokinshasa_6555.png",
    },
    {
        "name": "Джибуті",
        "iso": "DJ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofDjibouti_6547.png",
    },
    {
        "name": "Домініканська Республіка",
        "iso": "DO",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/dominican_republic_flags_flag_16991.png",
    },
    {
        "name": "Еквадор",
        "iso": "EC",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofEcuador_6543.png",
    },
    {
        "name": "Екваторіальна Гвінея",
        "iso": "GQ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofEquatorialGuinea_6539.png",
    },
    {
        "name": "Есватині",
        "iso": "SZ",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/1280px-Flag_of_Eswatini.svg.png",
    },
    {
        "name": "Еритрея",
        "iso": "ER",
        "flag": "https://cdn.icon-icons.com/icons2/2087/PNG/512/eritrea_icon_127765.png",
    },
    {
        "name": "Естонія",
        "iso": "EE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/estonia_flags_flag_16996.png",
    },
    {
        "name": "Ефіопія",
        "iso": "ET",
        "flag": "https://cdn.icon-icons.com/icons2/2087/PNG/512/ethiopia_icon_127767.png",
    },
    {
        "name": "Єгипет",
        "iso": "EG",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/egypt_flags_flag_16993.png",
    },
    {
        "name": "Ємен",
        "iso": "YE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/yemen_flags_flag_17086.png",
    },
    {
        "name": "Замбія",
        "iso": "ZM",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofzambia_6349.png",
    },
    {
        "name": "Зімбабве",
        "iso": "ZW",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofZimbabwe_6348.png",
    },
    {
        "name": "Ізраїль",
        "iso": "IL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/israelflag_6498.png",
    },
    {
        "name": "Індія",
        "iso": "IN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/india_flags_flag_17012.png",
    },
    {
        "name": "Ірак",
        "iso": "IQ",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/iraq_flags_flag_17015.png",
    },
    {
        "name": "Іран",
        "iso": "IR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/iran_flags_flag_17014.png",
    },
    {
        "name": "Ірландія",
        "iso": "IE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/ireland_flags_flag_17016.png",
    },
    {
        "name": "Ісландія",
        "iso": "IS",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/icelandflag_6505.png",
    },
    {
        "name": "Іспанія",
        "iso": "ES",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/spain_flags_flag_17068.png",
    },
    {
        "name": "Італія",
        "iso": "IT",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/italy_flags_flag_17018.png",
    },
    {
        "name": "Йорданія",
        "iso": "JO",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/jordan_flags_flag_17020.png",
    },
    {
        "name": "Казахстан",
        "iso": "KZ",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/kazakhstan_flags_flag_17021.png",
    },
    {
        "name": "Камбоджа",
        "iso": "KH",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/cambodia_flags_flag_16981.png",
    },
    {
        "name": "Камерун",
        "iso": "CM",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/cameroon_flags_flag_16982.png",
    },
    {
        "name": "Канада",
        "iso": "CA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/canada_flags_flag_16983.png",
    },
    {
        "name": "Катар",
        "iso": "QA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/qatar_flags_flag_17056.png",
    },
    {
        "name": "Кенія",
        "iso": "KE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/kenya_flags_flag_17022.png",
    },
    {
        "name": "Киргизстан",
        "iso": "KG",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofKyrgyzstan_6484.png",
    },
    {
        "name": "Китайська Народна Республіка",
        "iso": "CN",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagChineseFlag_banderadechina_6561.png",
    },
    {
        "name": "Кіпр",
        "iso": "CY",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/cyprus_flags_flag_16988.png",
    },
    {
        "name": "Колумбія",
        "iso": "CO",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/colombia_flags_flag_16986.png",
    },
    {
        "name": "Республіка Конго",
        "iso": "CG",
        "flag": "https://cdn.icon-icons.com/icons2/2087/PNG/512/republic_of_the_congo_icon_127752.png",
    },
    {
        "name": "Коста-Рика",
        "iso": "CR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/costa_rica_flags_flag_16966.png",
    },
    {
        "name": "Кот-д'Івуар",
        "iso": "CI",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofIvoryCoast_6496.png",
    },
    {
        "name": "Куба",
        "iso": "CU",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofCuba_6551.png",
    },
    {
        "name": "Кувейт",
        "iso": "KW",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/kuwait_flags_flag_17023.png",
    },
    {
        "name": "Лаос",
        "iso": "LA",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagoflaos_6483.png",
    },
    {
        "name": "Латвія",
        "iso": "LV",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofLatvia_6482.png",
    },
    {
        "name": "Лесото",
        "iso": "LS",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagoflesotho_6480.png",
    },
    {
        "name": "Литва",
        "iso": "LT",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/lithuaniaflag_6476.png",
    },
    {
        "name": "Ліберія",
        "iso": "LR",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofliberia_6479.png",
    },
    {
        "name": "Ліван",
        "iso": "LB",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/lebanon_flags_flag_17024.png",
    },
    {
        "name": "Лівія",
        "iso": "LY",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/libya_(new)_flags_flag_17025.png",
    },
    {
        "name": "Люксембург",
        "iso": "LU",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/luxembourg_flags_flag_17030.png",
    },
    {
        "name": "Мавританія",
        "iso": "MR",
        "flag": "https://cdn.icon-icons.com/icons2/1694/PNG/512/mrmauritaniaflag_111726.png",
    },
    {
        "name": "Мадагаскар",
        "iso": "MG",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/madagascar_flags_flag_17032.png",
    },
    {
        "name": "Малаві",
        "iso": "MW",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/MalawiFlag_6471.png",
    },
    {
        "name": "Малайзія",
        "iso": "MY",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/malaysia_flags_flag_17033.png",
    },
    {
        "name": "Малі",
        "iso": "ML",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/mali_flags_flag_17034.png",
    },
    {
        "name": "Марокко",
        "iso": "MA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/morocco_flags_flag_17039.png",
    },
    {
        "name": "Мексика",
        "iso": "MX",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/mexico_flags_flag_17036.png",
    },
    {
        "name": "Мозамбік",
        "iso": "MZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofmozambique_6453.png",
    },
    {
        "name": "Молдова",
        "iso": "MD",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/moldova_flags_flag_17037.png",
    },
    {
        "name": "Монголія",
        "iso": "MN",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofMongolia_6457.png",
    },
    {
        "name": "М'янма",
        "iso": "MM",
        "flag": "https://cdn.icon-icons.com/icons2/3105/PNG/512/flag_myanmar_asia_icon_191561.png",
    },
    {
        "name": "Намібія",
        "iso": "NA",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/namibiaflag_6451.png",
    },
    {
        "name": "Непал",
        "iso": "NP",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/nepalflag_6449.png",
    },
    {
        "name": "Нігер",
        "iso": "NE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/niger_flags_flag_17043.png",
    },
    {
        "name": "Нігерія",
        "iso": "NG",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/nigeria_flags_flag_17044.png",
    },
    {
        "name": "Нідерланди",
        "iso": "NL",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/netherlands_flags_flag_17041.png",
    },
    {
        "name": "Нікарагуа",
        "iso": "NI",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/NicaraguaFlag_6444.png",
    },
    {
        "name": "Німеччина",
        "iso": "DE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/germany_flags_flag_17001.png",
    },
    {
        "name": "Нова Зеландія",
        "iso": "NZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/NewZealandflag_nuevazelanda_6445.png",
    },
    {
        "name": "Норвегія",
        "iso": "NO",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/norway_flags_flag_17046.png",
    },
    {
        "name": "ОАЕ",
        "iso": "AE",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/uaeflag_emiratosarabesunido_6363.png",
    },
    {
        "name": "Оман",
        "iso": "OM",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofoman_6435.png",
    },
    {
        "name": "Пакистан",
        "iso": "PK",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/pakistan_flags_flag_17047.png",
    },
    {
        "name": "Панама",
        "iso": "PA",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/Panamaflag_6431.png",
    },
    {
        "name": "Папуа Нова Гвінея",
        "iso": "PG",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/papua_new_guinea_flags_flag_17049.png",
    },
    {
        "name": "Парагвай",
        "iso": "PY",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/paraguay_flags_flag_17050.png",
    },
    {
        "name": "Перу",
        "iso": "PE",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/peru_flags_flag_17051.png",
    },
    {
        "name": "ПАР",
        "iso": "ZA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/south_africa_flags_flag_17066.png",
    },
    {
        "name": "Південна Корея",
        "iso": "GS",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/south_korea_flags_flag_17067.png",
    },
    {
        "name": "Північна Корея",
        "iso": "KP",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofNorthKorea_6437.png",
    },
    {
        "name": "Північна Македонія",
        "iso": "MK",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofmacedonia_6473.png",
    },
    {
        "name": "Польща",
        "iso": "PL",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/poland_flags_flag_17053.png",
    },
    {
        "name": "Португалія",
        "iso": "PT",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/portugal_flags_flag_17054.png",
    },
    {
        "name": "Пуерто-Рико",
        "iso": "PR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/puerto_rico_flags_flag_17055.png",
    },
    {
        "name": "Росія",
        "iso": "RU",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/russiaflag_6419.png",
    },
    {
        "name": "Руанда",
        "iso": "RW",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofRwanda_6418.png",
    },
    {
        "name": "Румунія",
        "iso": "RO",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/romania_flags_flag_17057.png",
    },
    {
        "name": "Сальвадор",
        "iso": "SV",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/el_salvador_flags_flag_16994.png",
    },
    {
        "name": "Саудівська Аравія",
        "iso": "SA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/saudi_arabia_flags_flag_17059.png",
    },
    {
        "name": "Сенегал",
        "iso": "SN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/senegal_flags_flag_17061.png",
    },
    {
        "name": "Сербія",
        "iso": "RS",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/serbia_flags_flag_17062.png",
    },
    {
        "name": "Сирія",
        "iso": "SY",
        "flag": "https://cdn.icon-icons.com/icons2/1694/PNG/512/sysyriaflag_111908.png",
    },
    {
        "name": "Словаччина",
        "iso": "SK",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/slovakiaflag_6397.png",
    },
    {
        "name": "Словенія",
        "iso": "SI",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/slovenia_flags_flag_17065.png",
    },
    {
        "name": "Сомалі",
        "iso": "SO",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofsomalia_6393.png",
    },
    {
        "name": "США",
        "iso": "US",
        "flag": "https://cdn.icon-icons.com/icons2/230/PNG/256/UnitedStates_US_USA_840_Flag1_26093.png",
    },
    {
        "name": "Судан",
        "iso": "SD",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofSudan_6387.png",
    },
    {
        "name": "Суринам",
        "iso": "SR",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofSuriname_6386.png",
    },
    {
        "name": "Східний Тимор",
        "iso": "TL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/easttimorflag_timororiental_6544.png",
    },
    {
        "name": "Сьєрра-Леоне",
        "iso": "SL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofSierraLeone_6399.png",
    },
    {
        "name": "Таджикистан",
        "iso": "TJ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofTajikistan_6378.png",
    },
    {
        "name": "Таїланд",
        "iso": "TH",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/thailand_flags_flag_17072.png",
    },
    {
        "name": "Тайвань",
        "iso": "TW",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/taiwan_flags_flag_17071.png",
    },
    {
        "name": "Танзанія",
        "iso": "TZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofTanzania_6377.png",
    },
    {
        "name": "Того",
        "iso": "TG",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagoftogo_6374.png",
    },
    {
        "name": "Туреччина",
        "iso": "TR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/turkey_flags_flag_17074.png",
    },
    {
        "name": "Туркменістан",
        "iso": "TM",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofTurkmenistan_6368.png",
    },
    {
        "name": "Туніс",
        "iso": "TN",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/tunisia_flags_flag_17073.png",
    },
    {
        "name": "Уганда",
        "iso": "UG",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofuganda_6365.png",
    },
    {
        "name": "Угорщина",
        "iso": "HU",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofhungary_6506.png",
    },
    {
        "name": "Узбекистан",
        "iso": "UZ",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FlagofUzbekistan_6359.png",
    },
    {
        "name": "Україна",
        "iso": "UA",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/ukraine_flags_flag_17076.png"
    },
    {
        "name": "Уругвай",
        "iso": "UY",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/Uruguayflag_6360.png",
    },
    {
        "name": "Фінляндія",
        "iso": "FI",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/finlandflag_6530.png",
    },
    {
        "name": "Філіпіни",
        "iso": "PH",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/philippines_flags_flag_17052.png",
    },
    {
        "name": "Франція",
        "iso": "FR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/france_flags_flag_16999.png",
    },
    {
        "name": "Фолклендські острови",
        "iso": "FK",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/FalklandIslandsflag_islasmalvinas_6533.png",
    },
    {
        "name": "Хорватія",
        "iso": "HR",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/croatia_flags_flag_16987.png",
    },
    {
        "name": "Центральноафриканська Республіка",
        "iso": "CF",
        "flag": "https://cdn.icon-icons.com/icons2/2087/PNG/512/central_african_republic_icon_127794.png",
    },
    {
        "name": "Чад",
        "iso": "TD",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/chadflag_6563.png",
    },
    {
        "name": "Чехія",
        "iso": "CZ",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/czech_republic_flags_flag_16989.png",
    },
    {
        "name": "Чилі",
        "iso": "CL",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/Chileflag_6562.png",
    },
    {
        "name": "Чорногорія",
        "iso": "ME",
        "flag": "https://cdn.icon-icons.com/icons2/97/PNG/256/montenegro_flags_flag_17038.png",
    },
    {
        "name": "Швейцарія",
        "iso": "CH",
        "flag": "https://cdn.icon-icons.com/icons2/127/PNG/512/switzerland_flag_20393.png",
    },
    {
        "name": "Швеція",
        "iso": "SE",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/swedenflag_6382.png",
    },
    {
        "name": "Шрі-Ланка",
        "iso": "LK",
        "flag": "https://cdn.icon-icons.com/icons2/1694/PNG/512/lksrilankaflag_111718.png",
    },
    {
        "name": "Ямайка",
        "iso": "JM",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofjamaica_6495.png",
    },
    {
        "name": "Японія",
        "iso": "JP",
        "flag": "https://cdn.icon-icons.com/icons2/40/PNG/128/flagofjapan_6493.png",
    },
]